export const productConstants ={
    ADD_PRODUCT : 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_ERROR : 'ADD_PRODUCT_ERROR',
    LIST_PRODUCTS : 'LIST_PRODUCTS',
    LIST_PRODUCTS_SUCCESS : 'LIST_PRODUCTS_SUCCESS',
    LIST_PRODUCTS_ERROR : 'LIST_PRODUCTS_ERROR'
}
